#################################################################################################################################################
##### This file defines Kubernetes resources for deploying and exposing two services: book-catalog-service and inventory-management-service #####
############################# Incldues definitions for both Deployment and Service resources for each application. ##############################
#################################################################################################################################################

# Deployment for Book Catalog Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog-service
  template:
    metadata:
      labels:
        app: book-catalog-service
    spec:
      containers:
        - name: book-catalog-service
          image: book-catalog-service:1
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://cloud_native_part3_db_user:2lTh590rpWXqdnlWK0fWRHkrFjCacfXM@dpg-cqfecrt6l47c73bd1c2g-a.singapore-postgres.render.com/cloud_native_part3_db"
---
# Service for Book Catalog Service
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
---
# Deployment for Inventory Management Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  labels:
    app: inventory-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management-service
  template:
    metadata:
      labels:
        app: inventory-management-service
    spec:
      containers:
        - name: inventory-management-service
          image: inventory-management-service:1
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: "postgresql://admin:E5OJuKRE14iotwfsvHwJeqsjaKK1eKmO@dpg-cq0nb2aju9rs73b0500g-a.oregon-postgres.render.com/part2"
---
 # Servcie for Inventory Management Service 
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001